#!/usr/bin/env node
// ADR-007: copy the canonical contracts module into supabase/functions/_shared,
// rewriting the zod import for Deno. Deterministic: output depends only on the source.
// --check: fail (exit 2) if the deployed copy drifts from the source. Used by CI.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const banner = '// GENERATED by packages/contracts/scripts/sync-edge.mjs — do not edit.\n';
const units = [
  {
    src: resolve(here, '../src/index.ts'),
    dest: resolve(here, '../../../supabase/functions/_shared/contracts.ts'),
    rewrite: (s) => s.replace("from 'zod'", "from 'npm:zod@3'"),
  },
  {
    src: resolve(here, '../../router/src/index.ts'),
    dest: resolve(here, '../../../supabase/functions/_shared/router.ts'),
    rewrite: (s) => s.replaceAll("from 'contracts'", "from './contracts.ts'"),
  },
];

const check = process.argv.includes('--check');
let failed = false;
for (const { src, dest, rewrite } of units) {
  const generated = banner + rewrite(readFileSync(src, 'utf8'));
  const hash = createHash('sha256').update(generated).digest('hex');
  if (check) {
    let currentHash = '';
    try {
      currentHash = createHash('sha256').update(readFileSync(dest, 'utf8')).digest('hex');
    } catch {
      /* missing file → drift */
    }
    if (currentHash !== hash) {
      console.error(`CONTRACTS_DRIFT ${dest}: expected ${hash} — run sync-edge.mjs`);
      failed = true;
    } else {
      console.log(`CONTRACTS_SYNC_OK ${dest} ${hash}`);
    }
  } else {
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, generated);
    console.log(`CONTRACTS_SYNCED ${dest} ${hash}`);
  }
}
if (failed) process.exit(2);
