#!/usr/bin/env node
// ADR-007: copy the canonical contracts module into supabase/functions/_shared,
// rewriting the zod import for Deno. Deterministic: output depends only on the source.
// --check: fail (exit 2) if the deployed copy drifts from the source. Used by CI.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, '../src/index.ts');
const dest = resolve(here, '../../../supabase/functions/_shared/contracts.ts');

const banner = '// GENERATED by packages/contracts/scripts/sync-edge.mjs — do not edit.\n';
const generated =
  banner + readFileSync(src, 'utf8').replace("from 'zod'", "from 'npm:zod@3'");
const hash = createHash('sha256').update(generated).digest('hex');

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(dest, 'utf8');
  } catch {
    console.error(`CONTRACTS_DRIFT: ${dest} missing — run sync-edge.mjs`);
    process.exit(2);
  }
  const currentHash = createHash('sha256').update(current).digest('hex');
  if (currentHash !== hash) {
    console.error(`CONTRACTS_DRIFT: expected ${hash} got ${currentHash} — run sync-edge.mjs`);
    process.exit(2);
  }
  console.log(`CONTRACTS_SYNC_OK ${hash}`);
} else {
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, generated);
  console.log(`CONTRACTS_SYNCED ${hash}`);
}
