// GENERATED by packages/contracts/scripts/sync-edge.mjs — do not edit.
// GamePoint wire contracts — single source of truth (ADR-007).
// Consumed by: overlay (direct import), Edge Functions (synced copy via
// scripts/sync-edge.mjs), Rust dispatch crate (serde mirror, fixture-parity tested).
import { z } from 'npm:zod@3';

export const SCHEMA_VERSION = 1 as const;

const uuid = z.string().uuid();
const hex64 = z.string().regex(/^[0-9a-f]{64}$/, 'blake3 hex digest');

export const RoiKind = z.enum(['hud', 'minimap', 'tooltip', 'dialog', 'dense_text', 'other']);

export const RoiDescriptor = z.object({
  x: z.number().int().nonnegative(),
  y: z.number().int().nonnegative(),
  w: z.number().int().positive(),
  h: z.number().int().positive(),
  kind: RoiKind,
});

export const HotkeyIntent = z.enum(['assist', 'explain', 'recap']);

export const LocalObservables = z.object({
  process_name: z.string().max(256),
  window_title: z.string().max(512),
  title_slug_hint: z.string().max(128).nullable(),
  vision_fallback: z.boolean(), // true when process/window match failed and vision must identify
});

export const AssistRequest = z.object({
  schema_version: z.literal(SCHEMA_VERSION),
  session_id: uuid,
  title_id: uuid,
  ts_client_monotonic_ms: z.number().int().nonnegative(),
  frame_b64: z.string().min(1).max(8_000_000), // JPEG/WebP, base64 (ADR-006)
  frame_width: z.number().int().positive().max(16_384),
  frame_height: z.number().int().positive().max(16_384),
  roi_descriptors: z.array(RoiDescriptor).max(8),
  audio_opus_bytes: z.null(),      // ADR-003: frame-only v1.0, structurally enforced
  audio_duration_ms: z.literal(0), // ADR-003
  hotkey_intent: HotkeyIntent,
  local_observables: LocalObservables,
  blake3: hex64, // digest of raw (pre-base64) frame bytes
});

export const SourceTier = z.enum(['verified', 'mixed', 'policy', 'none']);

export const CoachingResponse = z
  .object({
    advice_text: z.string().min(1).max(2_000),
    recommended_action: z.string().min(1).max(300),
    evidence_ids: z.array(uuid).max(16),
    confidence: z.number().min(0).max(1),
    source_tier: SourceTier,
    not_verified: z.boolean(),
    latency_ms: z.number().int().nonnegative().optional(),
  })
  // Truth bar (§1.3): a claim carries evidence or is explicitly not verified.
  .refine((r) => r.evidence_ids.length > 0 || r.not_verified, {
    message: 'truth bar: evidence_ids required unless not_verified=true',
  });

export const AdviceOutcome = z.enum(['ok', 'degraded', 'refused_advantage', 'error']);

export const AdviceEventTelemetry = z.object({
  session_id: uuid,
  title_id: uuid,
  mode: z.string().max(32),
  model: z.string().max(128),
  latency_ms: z.number().int().nonnegative(),
  input_tokens: z.number().int().nonnegative(),
  output_tokens: z.number().int().nonnegative(),
  cost_usd_micros: z.number().int().nonnegative(),
  confidence: z.number().min(0).max(1),
  outcome: AdviceOutcome,
});

export const AssistBudget = z.object({
  maxInputTokens: z.number().int().positive(),
  maxOutputTokens: z.number().int().positive(),
  maxImagePixels: z.number().int().positive(),
  maxRois: z.number().int().positive(),
  maxRetrievalChunks: z.number().int().positive(),
  maxLatencyMs: z.number().int().positive(),
  maxCostUsdMicros: z.number().int().positive(),
  escalationAllowed: z.boolean(),
});

export type RoiDescriptor = z.infer<typeof RoiDescriptor>;
export type HotkeyIntent = z.infer<typeof HotkeyIntent>;
export type LocalObservables = z.infer<typeof LocalObservables>;
export type AssistRequest = z.infer<typeof AssistRequest>;
export type SourceTier = z.infer<typeof SourceTier>;
export type CoachingResponse = z.infer<typeof CoachingResponse>;
export type AdviceOutcome = z.infer<typeof AdviceOutcome>;
export type AdviceEventTelemetry = z.infer<typeof AdviceEventTelemetry>;
export type AssistBudget = z.infer<typeof AssistBudget>;

export const defaultFixtureBudget: AssistBudget = AssistBudget.parse({
  maxInputTokens: 1200,
  maxOutputTokens: 120,
  maxImagePixels: 786_432,
  maxRois: 2,
  maxRetrievalChunks: 4,
  maxLatencyMs: 1500,
  maxCostUsdMicros: 500,
  escalationAllowed: false,
});

/** Degraded response used on any inference failure — never a crash (§1.2). */
export const NO_ADVICE_THIS_FRAME: CoachingResponse = CoachingResponse.parse({
  advice_text: 'Not verified: no advice this frame.',
  recommended_action: 'none',
  evidence_ids: [],
  confidence: 0,
  source_tier: 'none',
  not_verified: true,
});

/** Refusal issued when the Advantage Check post-filter trips (§1.1.2). */
export const ADVANTAGE_REFUSAL: CoachingResponse = CoachingResponse.parse({
  advice_text:
    'GamePoint coaches decisions — it never calls out live opponent information you could not perceive yourself. Ask about builds, rotations, or macro strategy instead.',
  recommended_action: 'none',
  evidence_ids: [],
  confidence: 1,
  source_tier: 'policy',
  not_verified: true,
});
